# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nor Enibtawi
title: Software Tester
email: nor2004n.4@gmail.com
# email_title: Email (Email title override)
phone: 864-441-2358
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  norenibtawi1
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: nor-enibtawi
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pfp.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hey! My name is Nor Enibtawi. I was born and raised in Greenville, South Carolina. I'm currently a Junior student at Clemson University.
  I'm studying Computer Information Systems with a minor in Cybersecurity. I am currently proficient in C, C++, Python, and Java (Most experience with C++ and Java);
  I also have limited experience with Lua and JS. My goal is to work in the I.T. or Networking field.
  I'm a software tester with experience in mobile app QA and academic projects in Java, C++, and Python. I'm currently expanding my technical skills and looking for opportunities
  to grow not just as a developer, but as an IT professional who can support, secure, and improve the systems people rely on every day.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Checkers Game
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Terminal Based | Java | Intellij
        description: | # this will include new lines to allow paragraphs
          I worked on a team-developed Checkers game in Java where I helped build the core game engine, including move validation, 
          capturing logic, king progression, and overall game-state tracking. The project emphasized clean object-oriented design, 
          and I collaborated with teammates through Git to manage features and maintain consistent architecture, 
          and I also wrote unit tests to verify movement rules, turn order, and win conditions.
        
      - layout: left
        border:  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Chain Reaction Game
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Terminal Based | C++ | Vim
        description: | # this will include new lines to allow paragraphs
          I developed a terminal-based Chain Reaction strategy game in C++ on a Unix environment using Vim. 
          The project implemented full player logic, grid management, and cascading chain reaction mechanics to keep the system organized and expandable. 
        
  - title: Related Experience
    layout: list
    content:
      - layout: right
        title: Eleos Technologies
        sub_title: Software Tester
        caption: April 2025 - present
        link: https://eleostech.com/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I worked as a software tester for a mobile application, where I executed functional, 
          UI, and regression tests across multiple devices and operating system versions to ensure consistent performance and reliability. 
          I identified, reproduced, and documented bugs with clear steps and details, then collaborated with developers 
          to verify fixes and improve feature quality. The role involved structured test-case execution as well as exploratory testing to find edge cases and usability issues. 
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Clemson University
        sub_title: BS Computer Information Systems; Minor Cybersecurity
        caption: 2024 - present
        # quote: >
        #   Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Transfered from Greenville Technical College
      - layout: top-left
        title: Riverside Highschool
        sub_title: High School Degree
        caption: 2022
  - title: Personal Life
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of School and Work, I enjoy watching shows, playing video games, cooking, and going to the gym.
      I'm starting to pick up novice game development as a hobby, although I haven't sank much time into it yet.
      I am also a fan of Philosophy, and try to read every now and again.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
